// This class is autogenerated.
package com.foo.data;

/**
 * A Engineer.
 * @version 1.
 * @author unascribed.
 */

import lombok.*;
import java.util.*;

 @Data
 @EqualsAndHashCode(of = {"employeeId", "type", "department"} )
        @ToString(of = {"employeeId", "type", "department"} )
        public class Engineer extends com.foo.data.Employee {

        /**
         * Department.
        */
        @io.swagger.annotations.ApiModelProperty(value = "Department", required = true)
        private String department;

        /**
         * TODO.
        */
        @io.swagger.annotations.ApiModelProperty(value = "TODO", required = false)
        private com.foo.data.EngineerType type;


        /**
         * TODO.
        */
        @io.swagger.annotations.ApiModelProperty(value = "TODO", required = false)
        private List<String> phoneNumbers = new ArrayList<>();


        }
