// This class is autogenerated.
package ${dataElement.namespace};

/**
 * ${dataElement.documentation}.
 * @version ${dataElement.version}.
 * @author ${dataElement.author}.
 */

 import lombok.*;
 import java.util.*;

 @Data
 @EqualsAndHashCode(${dataElement.identifiers})
 @ToString(${dataElement.identifiers})
 <#if dataElement.extends>
 public class ${dataElement.name} extends ${dataElement.baseType} {
 <#else>
 public class ${dataElement.name} {
 </#if>

 <#list dataElement.fields as field>
    <#if field.array>

        /**
         * ${field.documentation}.
         */
        private List<${field.javaType}> ${field.name} = new ArrayList<>();

    <#else>
      /**
        * ${field.documentation}.
        */
        private ${field.javaType} ${field.name};
    </#if>

 </#list>
 }
